{% set name = "reducer" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5dbf203ab00bc8df8f10586364830ce84966ad81425723dfb4322c9642b7ab1d

build:
  noarch: python
  number: 0
  entry_points:
    - reducer = reducer:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.9
    - hatchling
    - hatch-vcs
  run:
    - python >=3.9
    - astropy >=4
    - numpy
    - scipy
    - scikit-image
    - ipywidgets >=7.5
    - msumastro >=1
    - ccdproc >=2
    - matplotlib-base
    - dask

test:
  imports:
    - reducer
  commands:
    - reducer --help

about:
  home: http://reducer.readthedocs.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Jupyter widget-based package for reducing FITS images
  description: |
    reducer provides a a widget interface in a Jupyter notebook to the ccdproc package
    for calibrating astronomical images.
  doc_url: http://reducer.readthedocs.org
  dev_url: https://github.com/mwcraig/reducer

extra:
  recipe-maintainers:
    - mwcraig
